services:  
  rest-service-db:
      image: postgres:16-alpine
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: scholeeadmin
      volumes:
        - "./prisma/migrations/db:/docker-entrypoint-initdb.d"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server

  rest-service:
    build: 
      context: ../rest-service
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    restart: always
    depends_on:
      - rest-service-db
      - redis
